name: GitHub Pages
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SynchrotronUI
        uses: actions/checkout@v4
      - name: Checkout Synchrotron
        uses: actions/checkout@v4
        with:
          repository: ThatOtherAndrew/Synchrotron
          path: synchrotron
      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Build site
        run: bun install && bun run build
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: synchrotron/.python-version
      - name: Build documentation
        run: uv run --directory synchrotron --only-dev mkdocs build --site-dir ../dist/docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
